### PR TITLE
US6921 - App Header

### PR DESCRIPTION
**Pull request by seancdavis**
As a Crossroads Connect user, 
I want to see the Connect branding in the top header of the Connect application

### CODE REVIEW

**Comment by seancdavis** [comment]
@tcmacdonald: Still need tests here (and still have that issue with the app test failing). I also should point out that I stripped the search bar out of the header and put it back into the neighbors component because it was causing too much of an issue.

**Comment by seancdavis** [comment]
@tcmacdonald: Test suite issue fixed, so now we're good minus writing new tests for features here.

**Comment by tcmacdonald** [comment]
Sorry @seancdavis – build failed. Can you take another look?

**Comment by seancdavis** [comment]
@tcmacdonald: Just pushed a couple more changes to help with the labels on the map falling behind the header (the labels were not respecting their boundaries for some reason).

**Comment by seancdavis** [comment]
@tcmacdonald: I think I did this correctly. @zarahzachz, @boggsey, and were overlapping a lot today, but I think I had this is ready to go. I had to move the localized search button.

**Pull request merged**
