### PR TITLE
DE3421 - Fix phone number text on host signup page.

### PR DESCRIPTION
**Pull request by zarahzachz**
On the host signup page, the phone number field reads "Contact Number" which is confusing. We're asking the user for a phone number so it should read "Phone Number". Don't forget to correct the error message too.

### CODE REVIEW

**Comment by zarahzachz** [comment]
@seancdavis I reverted some of that stuff back. Ready for review.

**Comment by seancdavis** [comment]
@zarahzachz: Please fix conflicts.

**Comment by zarahzachz** [comment]
@seancdavis I fixed the conflicts. Ready for review.

**Comment by seancdavis** [comment]
@zarahzachz: This looks good and is ready to go, but please resolve conflicts first.

**Comment by zarahzachz** [comment]
@seancdavis @tcmacdonald I fixed the conflicts. Ready for review.

**Pull request merged**
